#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR
./web_interface &

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd /usr/local/bin
# launch mongodb
./mongod
# cd $DIR

# load data from dump..